authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]     

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   #path('', mainapp.lessons, name='lk'),
   #path('<int:pk>/', mainapp.lessons, name='category'),
]

robotorium/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp
import authapp.views as authapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main),
    path('lk/', mainapp.lk),
    path('contact/', mainapp.contact),
    path('lk/1', mainapp.lesson1),
    path('lk/2', mainapp.lesson2),
    path('lk/3', mainapp.lesson3),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Teacher(AbstractUser):
    school = models.CharField(verbose_name='школа', max_length=32)

mainapp/models.py
from django.db import models


class Lesson(models.Model):
    name = models.CharField(verbose_name = 'урок', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    file_path = models.TextField(verbose_name='путь к презентации', blank=True)

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm

from .models import Teacher


class TeacherLoginForm(AuthenticationForm):
    class Meta:
        model = Teacher
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(TeacherLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import TeacherLoginForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'вход'

    login_form = TeacherLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/lk/')

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Lesson
from django.http import FileResponse, Http404


def main(request):
    return render(request, 'mainapp/robot-main.html')


def lk(request):
    if request.user.is_authenticated:
        return render(request, 'mainapp/robot-learn.html')
    else:
        return HttpResponseRedirect('/auth/login/')



def contact(request):
    return render(request, 'mainapp/contacts.html')


def lesson1(request):
    try:
        return FileResponse(open('media/lesson1.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404('not found')


def lesson2(request):
    try:
        return FileResponse(open('media/lesson2.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404('not found')


def lesson3(request):
    try:
        return FileResponse(open('media/lesson3.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404('not found')

authapp/templates/authapp/base.html
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title></title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/static/css/style.css" type="text/css" media="all">
    <link rel="apple-touch-icon" href="logo.jpg">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
</head>
<body>
<main role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 main-block mx-auto">
                <div class="row">
                    <div class="col-md-8 text-center mx-auto">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5 mx-auto mb-5">
                                                         {% block content %}

                                 {% endblock %}

                    </div>

                </div>
            </div>
        </div>
    </div>
</main>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}


{% block content %}

    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>


{% endblock %}

mainapp/templates/mainapp/robot-main.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title></title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/static/css/style.css" type="text/css" media="all">
    <link rel="apple-touch-icon" href="logo.jpg">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
</head>
<body>
<main role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-12  mt-4">
                <div class="row">

                    <div class="col-md-4">
                        <a href="auth/login/" class="underline">
                            <div class="form-login enter text-white text-center mt-5">
                                <span>Вход</span>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <p>
                Страничка дипломного проекта
            </p>
        </div>
        <div class="col-md-12 main-block main-block-page w-border mt-5 mx-auto">
            <div class="row">
                <div class="p-5">
                    <h1>Новости</h1>
                    <div class="pl-5 mt-4">
                        <p>
                            Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру сгенерировать несколько абзацев
                            более
                            менее осмысленного текста рыбы на русском языке.
                        </p>
                        <p>
                            Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру сгенерировать несколько абзацев
                            более
                            менее осмысленного текста рыбы на русском языке.
                        </p>
                        <p>
                            Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру сгенерировать несколько абзацев
                            более
                            менее осмысленного текста рыбы на русском языке.
                        </p>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        </div>
    </div>
    </div>
    </div>
</main>
</body>
</html>